[package]
name = "risc0-circuit-rv32im-v2-sys"
description = "Generated HAL code for rv32im-v2 cicuit"
version = "0.1.1"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
links = "risc0-circuit-rv32im-v2-sys"

[dependencies]
cust = { version = "0.3", optional = true }
derive_more = { version = "1.0", features = ["debug"] }
risc0-core = { workspace = true }
risc0-sys = { workspace = true }
sppark = { workspace = true, optional = true }

[build-dependencies]
cc = { version = "1.2.2", features = ["parallel"] }
glob = "0.3"
risc0-build-kernel = { workspace = true }

[features]
default = []
cuda = ["dep:cust", "dep:sppark", "risc0-sys/cuda"]
metal = []
