[package]
name = "risc0-circuit-keccak-methods"
version = { workspace = true }
edition = { workspace = true }

[package.metadata.release]
release = false

[build-dependencies]
risc0-build = { workspace = true }

[package.metadata.risc0]
methods = ["guest"]
