[workspace]
resolver = "2"
members = [
  "json-validate",
  "json-validate/core",
  "json-verify",
  "encrypt-aesgcm",
  "encrypt-aesgcm/core",
]

# Always optimize; otherwise tests take excessively long.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
